model:
  fn: infection.networks.FullGN
  kwargs:
    in_edge_features_shape: 2
    in_node_features_shape: 4
    out_edge_features_shape: 1
    out_node_features_shape: 1
    out_global_features_shape: 1
